name = "BDF"
uuid = "0f5c7595-fa0c-55c8-9031-265ea63f34cf"
authors = ["Samuele Carcagno"]
version = "0.5.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"

[compat]
HDF5 = "0.15"
Compat = "3.37"
DocStringExtensions = "0.8"
julia = "1.4"
